export const CREATE_SCOREBOARD_REQUEST = 'CREATE_SCOREBOARD_REQUEST';
export const CREATE_SCOREBOARD_SUCCESS = 'CREATE_SCOREBOARD_SUCCESS';
export const CREATE_SCOREBOARD_FAILURE = 'CREATE_SCOREBOARD_FAILURE';
