export const FETCH_SCOREBOARDS_REQUEST = 'FETCH_SCOREBOARDS_REQUEST';
export const FETCH_SCOREBOARDS_SUCCESS = 'FETCH_SCOREBOARDS_SUCCESS';
export const FETCH_SCOREBOARDS_FAILURE = 'FETCH_SCOREBOARDS_FAILURE';
