export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';

export const FETCH_FETCH_SEARCH_EMPLOYEES_REQUEST =
  'FETCH_FETCH_SEARCH_EMPLOYEES_REQUEST';
export const FETCH_FETCH_SEARCH_EMPLOYEES_SUCCESS =
  'FETCH_FETCH_SEARCH_EMPLOYEES_SUCCESS';
export const FETCH_FETCH_SEARCH_EMPLOYEES_FAILURE =
  'FETCH_FETCH_SEARCH_EMPLOYEES_FAILURE';
